spring.main.allow-circular-references: true
datadump.location:
    author: C:\Users\sfjil\Documents\Spring\betterreads-data-loader\src\main\resources\test-authors.txt
    works: C:\Users\sfjil\Documents\Spring\betterreads-data-loader\src\main\resources\test-works.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: your-username
      password: your-password
      schema-action: create_if_not_exists
      request:
        timeout: 20s
      connection:
        connect-timeout: 20s
        init-query-timeout: 20s
  application:
    name: betterreads

datastax.astra:
  secure-connect-bundle: secure-connect-betterreads.zip

astra:
  db:
    id: astra-id
    region: europe-west1
    keyspace: main
    application:
      token: AstraCS:your-token
